java -jar ../external-tools/compiler.jar ^
  --js ../scripts/ode/extras.js ^
  --js ../scripts/ode/base.js ^
  --js ../scripts/ode/exceptions.js ^
  --js ../scripts/ode/lexer.js ^
  --js ../scripts/ode/nodes.js ^
  --js ../scripts/ode/parser.js ^
  --js ../scripts/ode/symboltable.js ^
  --js ../scripts/ode/stacks.js ^
  --js ../scripts/ode/interpreter.js ^
  --js ../scripts/ode/natives.js ^
  --js ../scripts/ode/controller.js ^
  --js_output_file ../scripts/ode-compiled.js ^
  --jscomp_error=deprecated ^
  --jscomp_error=visibility ^
  --jscomp_error=accessControls ^
  --jscomp_error=fileoverviewTags ^
  --jscomp_error=strictModuleDepCheck ^
  --jscomp_error=missingProperties ^
  --jscomp_error=unknownDefines ^
  --jscomp_error=checkTypes ^
  --warning_level VERBOSE